name: Update BGP Prefix Data

on:
  schedule:
    # Roda todos os dias às 03:00 AM UTC
    - cron: '0 3 * * *'
  workflow_dispatch: # Permite rodar manualmente para testes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.6' # Versão estável do Go

      - name: Run Processor
        run: |
          # Cria a pasta se não existir, executa o código Go
          go run main.go

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # O commit será feito no branch gh-pages
          publish_branch: gh-pages 
          force_orphan: true # Mantém o histórico limpo, focado nos dados atuais
